server:
  port: 8085
spring:
  application:
    name: bus

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Vishal219175/Config-service--MRCTC
          clone-on-start: true
